name: responsive_builder2
description: A set of widgets that can be used to define a readable responsive UI for widgets.
version: 0.9.0
homepage: https://github.com/Corkscrews/responsive_builder

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
